services:
  - type: web
    name: sonic-movies
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --verbosity 3
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: sonic-movie.onrender.com,.onrender.com
      - key: TMDB_API_KEY
        sync: false 