# Generated by Django 5.2.1 on 2025-05-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250516_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedsong',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='playlist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='LikedSong',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
